name: Format Pull Request Files

permissions:
  contents: write
  
on:
  push:
    branches: [main]
  issue_comment:
    types: [created]

env:
  bashPass: \033[32;1mPASSED -
  bashInfo: \033[33;1mINFO -
  bashFail: \033[31;1mFAILED -
  bashEnd:  \033[0m

jobs:
  Formatting:
    name: Run Formatting Check
    if: ${{ github.event.issue.pull_request &&
        ( ( github.event.comment.body == '/bot run uncrustify' ) ||
          ( github.event.comment.body == '/bot run formatting' ) ) }}
    runs-on: ubuntu-latest
    steps:
    - name: Apply Formatting Fix of Common Files
      id: check-formatting-of-common
      uses: z-sn/CI-Action/formatting-bot@main
      continue-on-error: true
      with:
        path: format_test/
